"""Insert-only registry ingestion: existing listings require a separate review."""

import hashlib
import re


def registry_payload(record):
    if not isinstance(record, dict):
        raise ValueError("Registry record must be an object")
    fields = {"title": 180, "rera_id": 100, "developer": 250, "location": 500}
    payload = {}
    for name, maximum in fields.items():
        value = record.get(name)
        if value is None:
            continue
        if not isinstance(value, str) or len(value.strip()) > maximum:
            raise ValueError("Invalid registry field: " + name)
        if value.strip():
            payload[name] = value.strip()
    if not payload.get("title") or not payload.get("rera_id"):
        raise ValueError("Registry title and RERA ID are required")
    base = re.sub(r"[^a-z0-9]+", "-", payload["title"].lower()).strip("-")[:120] or "project"
    suffix = hashlib.sha256(payload["rera_id"].encode()).hexdigest()[:16]
    payload.update(
        slug=f"{base}-{suffix}", country="India", state="Maharashtra",
        source_type="registry", ingestion_source="MahaRERA", verified=False,
    )
    return payload


def insert_registry_batch(client, records):
    # Validate the whole batch before issuing any write. IDs are generated by Postgres.
    payloads = [registry_payload(record) for record in records]
    if not payloads:
        return 0
    # ON CONFLICT DO NOTHING preserves URLs, owner edits, media and moderation.
    response = client.table("properties").upsert(
        payloads, on_conflict="rera_id", ignore_duplicates=True,
    ).execute()
    return len(response.data or [])
