"use client"
import { useState } from "react"
import Link from "next/link"
import JourneyNav from "@/components/real-estate/JourneyNav"
import BottomNav from "@/components/mobile/BottomNav"
import { estimateRepayment } from "@/lib/real-estate/repayment"
import styles from "@/components/real-estate/Listing.module.css"
export default function PropertyTools() {
 const [principal,setPrincipal]=useState("")
 const [rate,setRate]=useState("")
 const [years,setYears]=useState("")
 const [currency,setCurrency]=useState("INR")
 const result=principal && rate && years ? estimateRepayment(Number(principal),Number(rate),Number(years)) : null
 const money=(amount:number)=>new Intl.NumberFormat("en",{style:"currency",currency,maximumFractionDigits:0}).format(amount)
 return <main className="gth-container pt-8 pb-28"><JourneyNav/><p className="gold-text text-xs uppercase tracking-widest">Plan your next move</p><h1 className="text-3xl md:text-4xl font-bold mt-3">Property tools & buying checklist</h1><p className="opacity-70 mt-4 leading-7">Compare your options and prepare the questions that matter.</p><div className={styles.toolsLayout}>
 <section className="gth-glass rounded-3xl p-6 md:p-8"><h2 className="text-2xl font-bold">Monthly repayment estimate</h2><p className="text-sm opacity-70 mt-3">Enter your own loan figures. Currency changes the display label; it does not convert amounts.</p><div className={styles.toolInputs}><label>Currency<select value={currency} onChange={event=>setCurrency(event.target.value)}>{["INR","AED","USD","GBP","EUR","SGD"].map(value=><option key={value}>{value}</option>)}</select></label><label>Loan amount<input type="number" inputMode="decimal" min="1" max="1000000000000" value={principal} onChange={event=>setPrincipal(event.target.value)}/></label><label>Annual interest rate (%)<input type="number" inputMode="decimal" min="0" max="40" step="0.01" value={rate} onChange={event=>setRate(event.target.value)}/></label><label>Loan term (years)<input type="number" inputMode="numeric" min="1" max="40" step="1" value={years} onChange={event=>setYears(event.target.value)}/></label></div><div className={styles.toolResult} aria-live="polite">{result ? <><p className="text-sm opacity-70">Estimated monthly repayment</p><p className="gold-text text-3xl font-bold mt-3">{money(result.monthly)}</p><dl className="grid gap-3 mt-5"><div><dt className="text-sm opacity-70">Total repayment</dt><dd>{money(result.total)}</dd></div><div><dt className="text-sm opacity-70">Total interest</dt><dd>{money(result.interest)}</dd></div></dl></> : <p>Enter an amount, a rate from 0–40%, and a whole-number term from 1–40 years.</p>}</div><p className="text-xs opacity-70 leading-6">Fixed-rate amortization estimate. Fees, taxes, insurance and rate changes are excluded. This tool does not submit a loan application.</p></section>
 <section className="gth-glass rounded-3xl p-6 md:p-8"><h2 className="text-2xl font-bold">Before you choose a property</h2><ol className="list-decimal pl-5 space-y-5 leading-7 mt-6"><li>Check the recorded address, registration reference and developer against source documents.</li><li>Confirm current availability, asking price, currency and all additional charges with the listing contact.</li><li>Request the floor plan and clarify carpet area, built-up area and measurement units.</li><li>Arrange a site visit and inspect the property or the project progress.</li><li>Have the ownership, permissions and agreement reviewed before committing funds.</li></ol><div className="flex flex-wrap gap-3 mt-7"><Link href="/real-estate/saved" className={`gth-btn ${styles.action}`}>Compare your shortlist</Link><Link href="/real-estate" className={`gth-btn-gold ${styles.action}`}>Explore properties</Link></div></section></div><BottomNav/></main>
}
